### ISSUE TITLE
Translations bug? "quote for woocommerce"

### ISSUE THREAD

**Issue by Jaxisme** [pinalj/quotes-for-woocommerce#37]
Hello,
The quote plugin works very well!
Except, when i change language (i Use WPML) i still see the cart. (the bypass to quote is not working in other languages)
I use three languages, the plugin works only on english
i've seen somewhere that i could update languages in wpml string translation, but unfortunately i do not have those files??
Did i miss something?
What do i have to do, so the plugin works in all languages? 
thanks for the help
jax

**Comment by pinalj** [comment]
Make the plugin compatible with WPML & Polylang Pro
