### ISSUE TITLE
Checkout endpoints customization

### ISSUE THREAD

**Issue by ArneSaknussemm** [pinalj/quotes-for-woocommerce#54]
Hi Pinal, I love your plugin, thank you very much.
I was wondering if you can add some settings in order to change the order-received/order-pay pages according to the order status.
When a client requests a quote and latter when a he pay for it he gets the same page title: "order received". Maybe in english is ok, but in spanish is ambigous.
On the other hand, there is [this issue](https://wordpress.org/support/topic/removing-price-subtotal-and-total-field-from-the-cart-and-checkouts/) about removing unused fields from Checkouts tables.
So I came up with this snippet that allows you to set different titles and body classes according the checkout instance you are in. In this way you can hide subtotal and total on the first order-received, when the clients just request a quote, and show them on the second order-received, when the client had paid for it. Maybe it's ugly code but you can graciously integrate with your quote payment method.
Kind regards from Chile!
```
add_filter( 'the_title', 'thankyou_title', 999, 2 );
add_filter( 'body_class', 'thankyou_class' );

function thankyou_title($title, $post_id)
{
	if (is_wc_endpoint_url( 'order-received' ) && $post_id==15) //  checkout page id=15
	{
		global $wp;

		$order_id  = absint( $wp->query_vars['order-received'] );

		$order = new WC_Order( $order_id );
		if ( in_array($order->get_status(), ['completed', 'on-hold']) )
		{
			return 'Pedido realizado';
		}
		elseif ( $order->get_status() === 'pending')
		{
			return 'Solicitud de cotización enviada';
		}
	}
	elseif (is_wc_endpoint_url( 'order-pay' ) && $post_id==15)
	{
		return 'Pagar por el pedido';
	}
	return $title;
}
function thankyou_class( $classes )
{
	if (is_wc_endpoint_url( 'order-received' ))
	{
		global $wp;

		$order_id  = absint( $wp->query_vars['order-received'] );

		$order = new WC_Order( $order_id );
		if ( in_array($order->get_status(), ['completed', 'on-hold']) )
		{
			$classes[]='ready-to-go';
		}
		elseif ( $order->get_status() === 'pending')
		{
			$classes[]='pending';
		}
	}
	return $classes;
}
```

**Comment by ArneSaknussemm** [comment]
Any thoughts on this?

**Comment by pinalj** [comment]
Hi Francisco,

Sorry for not replying to you earlier. Yes, I'll be sure to include it in the upcoming update (scheduled in Jan '22). Thanks for sharing the code.

**Comment by ArneSaknussemm** [comment]
Great!

**Comment by pinalj** [comment]
Hi @ArneSaknussemm,

I was working on integrating the code you shared above into the plugin. However, I had a query:

You have mentioned the classes `pending` & `ready-to-go`. I believe there would be some custom css that needs to be included for these classes to work. Would these classes simply hide/show the subtotal, total etc. fields?

Also, secondly you are changing the page title based on the order status. My understanding of these is as below:

1. `return 'Pedido realizado';` - should appear once the user has paid for the quote.
2. `return 'Solicitud de cotización enviada';` - when the user is on the Order Received page after completing the submission of the quote request.
3. `return 'Pagar por el pedido';` - when the user comes to pay for the quote.

Can you kindly confirm the same. Once you do, I think I'll have to include more settings or provide filters for users to be able to change the text as per their choice.

**Comment by ArneSaknussemm** [comment]
Hi!
I ended up making a little plugin to apply my tweaks into my web sites. 
I've uploaded [here](https://github.com/ArneSaknussemm/quotes-tweaks)
I've removed this line
`if (is_wc_endpoint_url( 'order-received' ) && $post_id==15) //  checkout page id=15`
I was giving the checkout page id because otherwise the navigation menus items titles also changes.
But you can do this with in_the_loop() function.
I've also did a little function in order to get the order-received status.
There is a wp_enqueue_scripts action to enqueue the custom css, but some classes are not WooCommerce and have to do with my theme layout (Kadence Theme). Yes, the css only hides the total, subtotal, price columns, etc.
Regarding page titles, yes, your descriptions are absolutely correct. I've removed "Pagar por el pedido" ("Pay for order") because was unnecessary.
```
function titulos_cotizador($title, $post_id)
{
	if (is_checkout() && in_the_loop())
	{
		if (cart_contains_quotable()) return 'Finalizar Cotización';
		elseif (orden_recibida_estado()=='pending')	return 'Solicitud de cotización enviada';
		elseif (!empty(orden_recibida_estado())) return 'Pago realizado';
	}
	return $title;
}
```
I don't remember the exact logic of my new titles function, I know it works for me, if you need I can study it and comment it to you.
I think it would be great creating a new order status(es) "pending-quote" and/or "quote-complete" because "pending" is used with bac payment.

**Comment by pinalj** [comment]
Hi @ArneSaknussemm 

Thanks for reverting. I have included the endpoints check and title changes with some modifications in the next release.

`if ( is_wc_endpoint_url( 'order-received' ) && wc_get_page_id( 'checkout' ) === $id ) {
	global $wp;

	$order_id     = absint( $wp->query_vars['order-received'] );
	$order        = new WC_Order( $order_id );
	$order_status = $order->get_status();
	if ( in_array( $order_status, array( 'completed', 'on-hold' ) ) ) { // phpcs:ignore
		$title = apply_filters( 'qwc_change_checkout_page_title', $title, 'order-received', $order_status );
	} elseif ( $order->get_status() === 'pending' ) {
		$title = apply_filters( 'qwc_change_checkout_page_title', $title, 'order-received', $order_status );
	}
} elseif ( is_wc_endpoint_url( 'order-pay' ) && wc_get_page_id( 'checkout' ) === $id ) {
	$title = apply_filters( 'qwc_change_checkout_page_title', $title, 'order-pay', 'pending' );
}
return $title;`

This basically adds a filter thereby allowing the users to modify the title as needed. The filter has the below parameters:
1. default WC page title
2. checkout endpoint
3. order status

I'm going to incorporate the CSS changes in a later release as extensive testing will be needed to ensure it works across themes.

I'll definitely take into consideration the creation of a custom order status for quotes.

Thanks once again!

Pinal
