### ISSUE TITLE
Suggestion regarding price visibilitly on dashboard products screen

### ISSUE THREAD

**Issue by ArneSaknussemm** [pinalj/quotes-for-woocommerce#60]
Hi! A client ask me to show the product prices only in the back end. I did it changing
`if ( isset( $enable_quote ) && 'on' === $enable_quote ) {`
to
`if ( isset( $enable_quote ) && 'on' === $enable_quote && !is_admin() ) {`
on class-quotes-wc.php
It would be nice to have this option!
Regards,
Francisco

**Comment by pinalj** [comment]
Not sure I got you. The quote setting is applied only on the front end. The admin end (WP dashboard) should always show the prices.

**Comment by ArneSaknussemm** [comment]
I've quoted the v1.7.3 class-quotes-wc.php. In the v1.8 the qwc_remove_prices function is different.
Anyway, the change is simpler:
The line 225 is this:
`$enable_quote = product_quote_enabled( $post->ID );`
With show prices option disabled, this function applies on both back and front-end:
![image](https://user-images.githubusercontent.com/60868628/147414684-4f1d5e45-50a5-4031-9afd-496510645400.png)
In order to show the price only on back-end now I've added !is_admin() to that line
`$enable_quote = product_quote_enabled( $post->ID ) && !is_admin();`
So now I've got:
![image](https://user-images.githubusercontent.com/60868628/147414663-3ea9a302-be21-4821-8ebe-e41e8de2a312.png)
I suggest a filter or and option to allow this.
